name: Build the Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tokyo-Night-Dark-Enhanced
          path: ./dist
